// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordToggleController from "./password_toggle_controller"
application.register("password-toggle", PasswordToggleController)

import PaymentRequestRemainingAmountsController from "./payment_request_remaining_amounts_controller"
application.register("payment-request-remaining-amounts", PaymentRequestRemainingAmountsController)

import PaymentRequestTaxesController from "./payment_request_taxes_controller"
application.register("payment-request-taxes", PaymentRequestTaxesController)

import PriceFormatController from "./price_format_controller"
application.register("price-format", PriceFormatController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import TagifyController from "./tagify_controller"
application.register("tagify", TagifyController)
