require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/brands", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Brand. As you add validations to Brand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:brand).attributes
  }

  let(:invalid_attributes) {
    { logo: nil, name: nil }
  }

  let!(:organization) { create(:organization) }
  let!(:user) { create(:admin, organization: organization) }
  let!(:brand) { create(:brand, organization: organization) }

  let!(:other_organization) { create(:organization) }
  let!(:other_user) { create(:admin, organization: other_organization) }
  let!(:other_brand) { create(:brand, organization: other_organization) }

  let!(:super_admin) { create(:super_admin) }

  before do
    sign_in user
  end


  describe "GET /index" do
    it "renders a successful response" do
      get brands_url
      expect(response).to be_successful
    end

    it "shows only the brands from the user organization" do
      get brands_url
      expect(response.body).to include(brand.name)
      expect(response.body).not_to include(other_brand.name)
    end

    it "shows all brands to super admins" do
      sign_out user
      sign_in super_admin

      get brands_url
      expect(response.body).to include(brand.name)
      expect(response.body).to include(other_brand.name)
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get brand_url(brand)
      expect(response).to be_successful
    end

    it "returns a 404 when the brand is from another organization" do
      get brand_url(other_brand)
      expect(response).to have_http_status(:not_found)
    end

    it "shows all brands to super admins" do
      sign_out user
      sign_in super_admin

      get brand_url(other_brand)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_brand_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      get edit_brand_url(brand)
      expect(response).to be_successful
    end

    it "returns a 404 when the brand is from another organization" do
      get edit_brand_url(other_brand)
      expect(response).to have_http_status(:not_found)
    end

    it "shows all brands to super admins" do
      sign_out user
      sign_in super_admin

      get edit_brand_url(other_brand)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Brand" do
        expect {
          post brands_url, params: { brand: valid_attributes }
        }.to change(Brand, :count).by(1)
      end

      it "assigns the current user as the brand's organization" do
        post brands_url, params: { brand: valid_attributes }
        expect(Brand.last.organization).to eq(user.organization)
      end

      it "redirects to the created brand" do
        post brands_url, params: { brand: valid_attributes }
        expect(response).to redirect_to(brand_url(Brand.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Brand" do
        expect {
          post brands_url, params: { brand: invalid_attributes }
        }.to change(Brand, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post brands_url, params: { brand: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: 'New Brand' }
      }

      it "updates the requested brand" do
        patch brand_url(brand), params: { brand: new_attributes }
        brand.reload

        expect(brand.name).to eq('New Brand')
      end

      it "redirects to the brand" do
        patch brand_url(brand), params: { brand: new_attributes }
        brand.reload
        expect(response).to redirect_to(brand_url(brand))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch brand_url(brand), params: { brand: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it "returns a 404 when the brand is from another organization" do
        patch brand_url(other_brand), params: { brand: { name: 'New Brand' } }
        expect(response).to have_http_status(:not_found)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested brand" do
      expect {
        delete brand_url(brand)
      }.to change(Brand.kept, :count).by(-1)
    end

    it "redirects to the brands list" do
      delete brand_url(brand)
      expect(response).to redirect_to(brands_url)
    end

    it "returns a 404 when the brand is from another organization" do
      delete brand_url(other_brand)
      expect(response).to have_http_status(:not_found)
    end
  end
end
