require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/managements", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Management. As you add validations to Management, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "test", phone: "081234567890", no_ktp: "123456789012", no_npwp: "123456789012", bank_code: "123456789012", account_number: "123456789012", address: "test" }
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  let(:admin) { create(:admin) }

  before do
    sign_in admin
  end

  describe "GET /index" do
    it "renders a successful response" do
      Management.create! valid_attributes
      get managements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      management = Management.create! valid_attributes
      get management_url(management)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_management_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      management = Management.create! valid_attributes
      get edit_management_url(management)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Management" do
        expect {
          post managements_url, params: { management: valid_attributes }
        }.to change(Management, :count).by(1)
      end

      it "redirects to the created management" do
        post managements_url, params: { management: valid_attributes }
        expect(response).to redirect_to(management_url(Management.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Management" do
        expect {
          post managements_url, params: { management: invalid_attributes }
        }.to change(Management, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post managements_url, params: { management: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "test another", phone: "081234567890", no_ktp: "123456789012", no_npwp: "123456789012", bank_code: "123456789012", account_number: "123456789012", address: "test" }
      }

      it "updates the requested management" do
        management = Management.create! valid_attributes
        patch management_url(management), params: { management: new_attributes }
        management.reload
        expect(management.name).to eq("test another")
      end

      it "redirects to the management" do
        management = Management.create! valid_attributes
        patch management_url(management), params: { management: new_attributes }
        management.reload
        expect(response).to redirect_to(management_url(management))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        management = Management.create! valid_attributes
        patch management_url(management), params: { management: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested management" do
      management = Management.create! valid_attributes
      expect {
        delete management_url(management)
      }.to change(Management.kept, :count).by(-1)
    end

    it "redirects to the managements list" do
      management = Management.create! valid_attributes
      delete management_url(management)
      expect(response).to redirect_to(managements_url)
    end
  end
end
